name: Publish tracing-error

on:
  push:
    branches:
      - rigetti-main

jobs:
  publish:
    name: Publish tracing-error to rigetti-cargo
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Publish tracing-error
        run: cargo publish -p tracing-error --registry rigetti-cargo
